services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"

  zipcode-service:
    image: golang:latest
    container_name: zipcode-service
    ports:
      - "8080:8080"
    environment:
      - ZIPCODE_SERVICE_PORT=8080
      - WEATHER_SERVICE_PORT=8081
      - WEATHER_SERVICE_HOST=weather
    volumes:
      - .:/app
    command: >
      sh -c " cd /app && go mod tidy && GOOS=linux CGO_ENABLED=0 go build -ldflags='-w -s' -o ./build/zipcode-service ./cmd/zipcode-service/main.go && ./build/zipcode-service"
    depends_on:
      - zipkin

  weather:
    image: golang:latest
    container_name: weather
    ports:
      - "8081:8081"
    environment:
      - WEATHER_SERVICE_PORT=8081
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - .:/app
    command: >
      sh -c " cd /app && go mod tidy && GOOS=linux CGO_ENABLED=0 go build -ldflags='-w -s' -o ./build/weather-service ./cmd/weather-service/main.go && ./build/weather-service"
    depends_on:
      - zipkin
