services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"

  zipcode-service:
    build:
      context: .
      dockerfile: Dockerfile-zipcode
    container_name: zipcode-service
    ports:
      - "8080:8080"
    environment:
      - ZIPCODE_SERVICE_PORT=8080
      - WEATHER_SERVICE_PORT=8081
      - WEATHER_SERVICE_HOST=weather
    depends_on:
      - zipkin

  weather:
    build:
      context: .
      dockerfile: Dockerfile-weather
    container_name: weather
    ports:
      - "8081:8081"
    environment:
      - WEATHER_SERVICE_PORT=8081
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    depends_on:
      - zipkin
